name: ci 

on: push

env:
  SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  
jobs: 
  ci:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Run test 
        run: npm test
